### ISSUE TITLE
Invalid example code for topic "Tutorial: Creating a Type Provider (F#)"

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharpdocs#1]
Topic Url: https://msdn.microsoft.com/en-us/library/hh361034.aspx
Reported on twitter:  https://twitter.com/dannyrosalex/status/665492709247971328

<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/VisualFSharp">@VisualFSharp</a> <a href="https://twitter.com/hashtag/msdn?src=hash">#msdn</a> Legal F# code would be nice <a href="https://t.co/mXXukoInAh">https://t.co/mXXukoInAh</a> <a href="https://t.co/C4mkcZYfZW">pic.twitter.com/C4mkcZYfZW</a></p>&mdash; daniel rosales (@dannyrosalex) <a href="https://twitter.com/dannyrosalex/status/665492709247971328">November 14, 2015</a></blockquote> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

```
type Type1 =
    /// This is a static property.
    static member StaticProperty : string

    /// This constructor takes no arguments.
    new : unit -> Type1

    /// This constructor takes one argument.
    new : data:string -> Type1

    /// This is an instance property.
    member InstanceProperty : int

    /// This is an instance method.
    member InstanceMethod : x:int -> char

    /// This is an instance property.
    nested type NestedType = 
        /// This is StaticProperty1 on NestedType.
        static member StaticProperty1 : string
        …
        /// This is StaticProperty100 on NestedType.
        static member StaticProperty100 : string
````

**Comment by dend** [comment]
Fixed.
