### ISSUE TITLE
"ms.assetid" thing in "Lambda Expressions" article

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharpdocs#100]
https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/lambda-expressions-the-fun-keyword-[fsharp]

![image](https://cloud.githubusercontent.com/assets/873919/15567175/78e55960-232d-11e6-8f02-a7bf76df3e3f.png)

Also in https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/recursive-functions-the-rec-keyword-[fsharp]

**Comment by dend** [comment]
Fixed in #128
