### ISSUE TITLE
Wrong table formatting in "Computation Expressions" article

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharpdocs#103]
https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/computation-expressions-[fsharp]

![image](https://cloud.githubusercontent.com/assets/873919/15567403/ec49fb1c-232e-11e6-9d6e-492a449b3d11.png)

/cc @ReedCopsey

**Comment by dend** [comment]
Fixed in #128
