### ISSUE TITLE
A paragraph is all in bold font in "Asynchronous Workflows" article

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharpdocs#104]
https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/asynchronous-workflows-[fsharp]

![image](https://cloud.githubusercontent.com/assets/873919/15567562/c82f1c48-232f-11e6-8f5e-d89c9ac81778.png)

/cc @ReedCopsey

**Comment by dend** [comment]
Fixed in #128
