### ISSUE TITLE
Code is not formatted as snippet in "Flexible Types" article

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharpdocs#105]
https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/flexible-types-[fsharp]

![image](https://cloud.githubusercontent.com/assets/873919/15567636/0d486898-2330-11e6-823e-d19f861dda70.png)

**Comment by ReedCopsey** [comment]
@dend or @vasily-kirichenko Please close this now - Fixed.

**Comment by dend** [comment]
Looks good, thanks @ReedCopsey
