### ISSUE TITLE
"Overload:" artifact in "Assertions" article

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharpdocs#106]
https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/assertions-[fsharp]

![image](https://cloud.githubusercontent.com/assets/873919/15567815/16443ae8-2331-11e6-8c7d-c34ae9773a83.png)

I'm not sure, but it seems that `Overload:System.Diagnostics.Debug.Assert` should be a link.

**Comment by ReedCopsey** [comment]
I'll add "Overload:" to the list of bad prefixes I remove in #61

**Comment by ReedCopsey** [comment]
@dend or @vasily-kirichenko Please close this now. Fixed.

**Comment by dend** [comment]
@ReedCopsey there looks to be a note formatting issue. I will fix that and will update the bug after.

**Comment by ReedCopsey** [comment]
@dend So - are the braces actually required?

**Comment by dend** [comment]
@ReedCopsey nope, it's the location of the exclamation mark and the prefix.

**Comment by ReedCopsey** [comment]
@dend Does it need a space between the `>` and `!` ? I'll submit a PR to fix, if that's the issue.
