### ISSUE TITLE
Values column not wide enough in Core.Operators table

### ISSUE THREAD

**Issue by cartermp** [Microsoft/visualfsharpdocs#119]
Will this also be considered in the fix for #35?

This section: https://msdn.microsoft.com/visualfsharpdocs/conceptual/core.operators-module-%5bfsharp%5d#values

Looks like this on my laptop:

<img width="395" alt="screen shot 2016-05-26 at 12 50 27 pm" src="https://cloud.githubusercontent.com/assets/6309070/15587991/a6974568-2340-11e6-8917-3a43cbd90ecc.png">

And looks like this on my desktop:

![awkward-values](https://cloud.githubusercontent.com/assets/6309070/15588069/0d3d45ba-2341-11e6-9d9f-e0794e9ea123.PNG)

**Comment by ReedCopsey** [comment]
My understanding is that there was going to be a "global" change to the css
to fix table formatting.  Hopefully it will correct all of these pages, as
there's nothing in the page itself that should cause this to be a problem.

I think #35 will solve this one, and this is effectively a duplicate of
that issue.

**Comment by cartermp** [comment]
Sounds good.

**Comment by dend** [comment]
@ReedCopsey @cartermp correct.
