### ISSUE TITLE
Bold tags in text are not correctly displayed

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharpdocs#136]
https://msdn.microsoft.com/visualfsharpdocs/conceptual/properties-%5bfsharp%5d

In the remarks section at this text:  it's probably quite systemic.

>>>>
Private values that hold the data for properties are called *backing stores*. To have the compiler create the backing store automatically, use the keywords **member val**, omit the self-identifier, then provide an expression to initialize the property. If the property is to be mutable, include **with get, set**. For example, the following class type includes two automatically implemented properties. **Property1** is read-only and is initialized to the argument provided to the primary constructor, and **Property2** is a settable property initialized to an empty string:

**Comment by KevinRansom** [comment]
Oh the text is incorrectly specified as code for a few paragraphs.

**Comment by dend** [comment]
Assigning to myself to fix.

**Comment by dend** [comment]
@KevinRansom should be fixed in #137 - please validate and I will merge it.

**Comment by dend** [comment]
Fixed with #137 and validated.
