### ISSUE TITLE
query-expressions

### ISSUE THREAD

**Issue by CSharpFan** [Microsoft/visualfsharpdocs#14]
https://github.com/Microsoft/visualfsharpdocs/blob/live/docs/conceptual/query-expressions-[fsharp].md
Same here: 
https://msdn.microsoft.com/visualfsharpdocs/conceptual/query-expressions-%5bfsharp%5d
Is this the same source?
Something went wrong with the parsing here.

**Comment by dend** [comment]
Thanks for the report @CSharpFan - looking into it.

**Comment by dend** [comment]
I fixed the tables and the output. We are looking at snippet formatting now.
