### ISSUE TITLE
Inconsistent use of bold text in literals examples column

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharpdocs#151]
As you can see in this image, some literal examples are bold, others are shy.

![untitled](https://cloud.githubusercontent.com/assets/5175830/15763459/0c13817a-28d9-11e6-86e2-965efb768086.png)

https://msdn.microsoft.com/visualfsharpdocs/conceptual/literals-%5bfsharp%5d

**Comment by dend** [comment]
This fix will go live as part of #154 (already have it there). Thanks for the report!
