### ISSUE TITLE
The `with` keyword is missing documentation for record "manipulation"

### ISSUE THREAD

**Issue by ChrSteinert** [Microsoft/visualfsharpdocs#157]
The `with` keyword has multiple meanings in F# like Match or Type Expressions. The documentation for that is aggregated here: https://github.com/Microsoft/visualfsharpdocs/blob/live/docs/conceptual/keyword-reference-[fsharp].md
What seems to be missing (or I was not able to find it) is the documentation for the record manipulation/copying syntax. This is, what F# for fun and profit writes about here http://fsharpforfunandprofit.com/posts/correctness-immutability/ . Explicitly this part:
`let alice = {john with FirstName="Alice"}`
As it is an important part of the language it would be nice to have some official documentation for it (also that I know what it is called correctly ;) ).

**Comment by dend** [comment]
@KevinRansom @ReedCopsey - what do you think?

IMO this sounds like something you (@chrsteinert) can submit a PR for.

**Comment by ChrSteinert** [comment]
I agree. Would love to, yet need to know how it is called! :DAlso I'd like to get some guidance on where to put it etc.






On Fri, Jun 3, 2016 at 9:19 AM -0700, "Den Delimarsky" <notifications@github.com> wrote:





@KevinRansom @ReedCopsey - what do you think?

IMO this sounds like something you (@chrsteinert) can submit a PR for.

---

**Comment by ReedCopsey** [comment]
It's called a "copy and update record expression" (whew, that's a
mouthful!).

It's currently documented here:
https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/records-[fsharp]

I agree it's be nice to add to keywords.

Reed

**Comment by ChrSteinert** [comment]
What should I take for the `ms.assetid`?

**Comment by dend** [comment]
Are you creating a new article or adding content to the existing one?

If it's an existing article, the asset ID should be the same as it is today. If it's a new article, simply generate a new GUID and use it as the ID.
