### ISSUE TITLE
Documentation for Seq.tail is missing

### ISSUE THREAD

**Issue by ant0nsc** [Microsoft/visualfsharpdocs#180]
The latest FSharp libraries added `Seq.tail` in the `Collections.Seq` module. Source code is [here](https://github.com/fsharp/fsharp/blob/37a100b7caafde0f4df5a1924c9f65f4a18277a8/src/fsharp/FSharp.Core/seq.fs#L1794) However, the documentation is still missing for it.

**Comment by dend** [comment]
@cartermp @KevinRansom can you comment?

**Comment by KevinRansom** [comment]
@ant0nsc good eyes.  We would be happy to take a contribution adding the documentation for this Api.  I expect that there are other new api's that are also missing documentation.

I'm sure that @cartermp and @dend would be able to help 

Also marking this issue up for grab.

Kevin

**Comment by liboz** [comment]
So, as this issue mentions, there are many other functions that are missing from the docs.

I did a little bit of research and think most of the ones added in F# 4.0 haven't had docs made yet (https://github.com/fsharp/FSharpLangDesign/blob/master/FSharp-4.0/ListSeqArrayAdditions.md). Should I create a new issue for updating the docs for all the new functions or maybe it's easier to update this issue?

**Comment by dend** [comment]
@liboz I would recommend creating a new issue for the doc set that you mentioned.
