### ISSUE TITLE
Collections.Array Module documentation does not have the signature for Array.contains

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharpdocs#188]
This page here is missing Array.contains:  https://msdn.microsoft.com/visualfsharpdocs/conceptual/collections.array-module-%5bfsharp%5d

Array.contains : 'T -> 'T [] -> bool 

This page is missing List.contains:
https://msdn.microsoft.com/visualfsharpdocs/conceptual/collections.list-module-%5bfsharp%5d

List.contains : 'T -> 'T [] -> bool 

This page is missing Seq.contains

Seq.contains : 'T -> 'T [] -> bool

**Comment by liboz** [comment]
@KevinRansom Hey Array/List/Seq.contains all are on the module pages now after pull request #217. However, the links don't work yet because the GUIDs in the meta data for the individual documentation aren't linked yet. Not sure what needs to be done to fix that.

**Comment by ErikSchierboom** [comment]
I just checked, and as far as I can tell, the links are correctly displayed. So perhaps this issue could be closed?
