### ISSUE TITLE
GUID/assetid links do not work

### ISSUE THREAD

**Issue by liboz** [Microsoft/visualfsharpdocs#226]
For example for List.contains the first link, which uses the List.contains' assetid/GUID, does not work, but the second link directly to the file does work.

https://msdn.microsoft.com/library/52f70370-0c04-4823-bc6e-e92b60369420
https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/list.contains%5b't%5d-function-%5bfsharp%5d

Currently the assetid/GUID link is used on the collections.modules page and the direct file link is used in the TOC.

Related to #188

**Comment by dend** [comment]
You should not reference the doc by the GUID declared in the metadata - that is for reference purposes only. Instead, you should use relative links (use simple link Markdown syntax) using the name of the file.

**Comment by liboz** [comment]
@dend Does this apply even though the pre-existing links in say the [Collections.array module ](https://github.com/Microsoft/visualfsharpdocs/blob/master/docs/conceptual/collections.array-module-[fsharp].md) file use GUID links? That is to say if I were to add a new entry like `Array.distinct`, I should have it use a link to `array.distinct['t]-function-[fsharp].md`?

**Comment by dend** [comment]
@liboz correct. GUIDs that you see are GUIDs that point to older MSDN docs. Current conventions are using the file names (make sure to URL-encode those).
