### ISSUE TITLE
Missing indentation for the Event examples

### ISSUE THREAD

**Issue by mrakgr** [Microsoft/visualfsharpdocs#227]
The indentation for the examples on the [Events page](https://github.com/Microsoft/visualfsharpdocs/blob/live/docs/conceptual/events-[fsharp].md) is squished. It is squished for the later examples on the main [MSDN page](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/events-%5Bfsharp%5D) as well.

**Comment by dend** [comment]
@cartermp @KevinRansom @ReedCopsey - can you guys please look into this?

**Comment by cartermp** [comment]
Yep, I'll take care of this.

**Comment by dend** [comment]
Merged fix. Thanks @cartermp
