### ISSUE TITLE
Docmentation of the & operator

### ISSUE THREAD

**Issue by urbanhop** [Microsoft/visualfsharpdocs#248]
https://github.com/Microsoft/visualfsharpdocs/blob/live/docs/conceptual/symbol-and-operator-reference-[fsharp].md

says that the **& operator** has 2 uses:

1. Computes the address of a mutable value, for use when interoperating with other languages.
2. **Used in AND patterns**.

If the second point correct? How would you use & in an "AND" pattern?

**Comment by kbattocchi** [comment]
Yes, it's correct.  Here's a (pointless) example:

    let ((x,_) & (_,y)) = ('a',0)

**Comment by urbanhop** [comment]
bingo, thx.
