### ISSUE TITLE
failwith throws System.Exception, not Microsoft.FSharp.Core.FailureException

### ISSUE THREAD

**Issue by statpro-awebb** [Microsoft/visualfsharpdocs#25]
As noted by @dsyme and reported to Microsoft by me over a year ago, `failwith` throws `System.Exception` and not `Microsoft.FSharp.Core.FailureException`:-

https://github.com/fsharp/fsharp.github.io/issues/28#issuecomment-101332987

The published doc page is here:-

https://msdn.microsoft.com/visualfsharpdocs/conceptual/exceptions-the-failwith-function-[fsharp]

I will generate PR to fix.

**Comment by dend** [comment]
The PR was merged into master and synced to live. Doc update should be live within a couple of minutes.
