### ISSUE TITLE
The page for explicit fields has incorrect formatting

### ISSUE THREAD

**Issue by baronfel** [Microsoft/visualfsharpdocs#262]
https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/explicit-fields-the-val-keyword-%5bfsharp%5d

There are a few issues I've seen:

1. The 'front matter' for generation has leaked into the header of this page
1. The namespace links in the 'warning' section don't link to any pages
1. The page title is the 'ms.assetid'

**Comment by cartermp** [comment]
That page is deprecated in favor of this one: https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/members/explicit-fields-the-val-keyword

(1) and (3) are fixed, and (2) aren't links - if you think that's helpful, feel free to create an issue or make a [PR on the doc](https://github.com/dotnet/core-docs/blob/master/docs/fsharp/language-reference/members/explicit-fields-the-val-keyword.md#remarks).

**Comment by baronfel** [comment]
Ah, perfect. I just ran across that link via google when digging into a question Sergey Tihon had.  Thanks for the corrected links.

**Comment by cartermp** [comment]
No problem!  I guess redirects didn't pick this one up yet.  @dend, this page didn't seem to redirect properly.

**Comment by dend** [comment]
Issued a fix for this, sorry about the inconvenience folks!
