### ISSUE TITLE
:: (cons) operator prepends element to list, not appends

### ISSUE THREAD

**Issue by Andrew-Webb** [Microsoft/visualfsharpdocs#27]
File `docs/conceptual/symbol-and-operator-reference-[fsharp].md` says of the `::` operator:-

"The element on the left side is appended to the list on the right side."

But methinks this should be:-

"The element on the left side is prepended to the list on the right side."

**Comment by dsyme** [comment]
correct

**Comment by dend** [comment]
I merged the PR - it should be live shortly.
