### ISSUE TITLE
Group MD files into folder

### ISSUE THREAD

**Issue by forki** [Microsoft/visualfsharpdocs#3]
"Sorry, we had to truncate this directory to 1,000 files. 751 entries were omitted from the list."

even github can't dislay this properly

**Comment by jackfoxy** [comment]
@forki agree, would like to see folder structure like MSDN doc hierarchy

Visual F# Development Portal
(subfolders)
Visual F# Guided Tour
(subfolders)
Using Visual Studio to Write F# Programs
(subfolders)
F# Language Reference
(subfolders)
F# Compiler (fsc.exe) Reference
(subfolders)
F# Interactive (fsi.exe) Reference
(subfolders)
F# Core Library Reference
(subfolders)
Visual F# Samples and Walkthroughs
(subfolders)
Type Providers
(subfolders)

Or if there is some new planned hierarchy, use that one.

**Comment by KevinRansom** [comment]
As of now there is no planned hierarchy, and I believe we will be able to reorganize this however we want.  We are in no rush to reorganize it.  Let us first work with this for a short while, until we are comfortable that we understand the submission and re-integration processes before making significant changes

The proposed folder structure certainly seems like a viable and usefull one.

Kevin

**Comment by dend** [comment]
As @KevinRansom mentioned, right now there are no plans to re-structure the hierarchy, so I am going to close this for now.
