### ISSUE TITLE
Async.Catch code snippet is broken

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharpdocs#33]
https://msdn.microsoft.com/visualfsharpdocs/conceptual/async.catch%5b%27t%5d-method-%5bfsharp%5d

![image](https://cloud.githubusercontent.com/assets/873919/15331736/694380e0-1c6b-11e6-8f0b-206c5c0ebcaa.png)

**Comment by dend** [comment]
Just issued a fix. Let's see how it propagates. @vasily-kirichenko

**Comment by dend** [comment]
Fix is now live and the code snippet is fixed.
