### ISSUE TITLE
Contributor list in header shows 1{__global.contributor}}

### ISSUE THREAD

**Issue by akoeplinger** [Microsoft/visualfsharpdocs#34]
e.g. on https://msdn.microsoft.com/de-de/visualfsharpdocs/conceptual/visual-fsharp:

![image](https://cloud.githubusercontent.com/assets/1376924/15331896/b404314a-1c63-11e6-8ecb-29e127c35df3.png)

**Comment by dend** [comment]
Thank you for the report, @akoeplinger - looks like a recent bug. We're investigating.

**Comment by dend** [comment]
This should be fixed now.

**Comment by akoeplinger** [comment]
Thank you!
