### ISSUE TITLE
Add current F# release notes

### ISSUE THREAD

**Issue by eriawan** [Microsoft/visualfsharpdocs#39]
cc @dend @NumberByColors @KevinRansom @dsyme 

We need to have F# release notes included in MSDN Library documentation.

Now that VS 2015 is RTM, so the related version is F# 4.0. Therefore we should have something like "What's new in F# 4.0" page. 
Maybe we can start to copy the content from VIsual F# Github's CHANGELOG.MD:
https://github.com/Microsoft/visualfsharp/blob/master/CHANGELOG.md

After that we should refine the release note page to be more polished and fit for MSDN Library's common release note page. A good example to start is: ["What's new for VIsual C#" page](https://msdn.microsoft.com/en-us/library/hh156499.aspx)

Or we can create completely new page without referring to any page.

If this proposal is accepted, I'd love to volunteer myself to create this release notes page.

**Comment by KevinRansom** [comment]
Go ahead my friend, sounds like a great plan.

**Comment by dend** [comment]
Feel free to create the page, update the TOC and issue a PR - we will review and merge it once it passes the necessary validation checks.

**Comment by dend** [comment]
Once my current PR will be merged, I will create a new PR with the release notes.

**Comment by dend** [comment]
This is covered by #164 - @eriawan @cartermp @KevinRansom - please review.

**Comment by dend** [comment]
This is now live on our doc site: https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/whats-new-in-visual-fsharp

**Comment by eriawan** [comment]
@dend you got me quicker to submit the PR :)

apologize I was busy in the middle of some dev works. thanks, I'm reviewing it now.
