### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by Andrew-Webb** [Microsoft/visualfsharpdocs#40]
I know you're aware of some of these, and others have mentioned them in other issues, but I want to go through all the formatting issues I see here:-

https://msdn.microsoft.com/visualfsharpdocs/conceptual/exceptions-the-failwith-function-[fsharp]

* `title: Exceptions: The failwith Function (F#) description: Exceptions: The failwith Function (F#) keywords: visual f#, f#, functional programming author: dend manager: danielfe ms.date: 05/16/2016 ms.topic: language-reference ms.prod: visual-studio-dev14` needs formatting
* `ms.assetid: 2e0c1f28-cc6c-4ecd-bb93-3816c4dd7cd3` needs to change to something more friendly (note that it is linked to in the IN THIS ARTICLE column on the right of the page)
* `ms.assetid: 2e0c1f28-cc6c-4ecd-bb93-3816c4dd7cd3 | MSDN` isn't a useful title for the page
* too much leading vertical space in the `Syntax` box
* in the `Remarks` section, the box with the sample code in is kinda silly in that the code is not very long, but you have to click to reveal the final three lines; it would be better to just show the whole snippet
* the sample code box isn't labelled / titled (although it's obvious it's sample code)

I also question the continued use of the big blue "Is this page helpful? [Yes] [No]" banner that sticks to the bottom of the screen (until you dismiss it).  I've never found those things,er, helpful in any way.  Plus it's big and bold and demands attention (click on Yes or click on No, or click on 'x' - but what happens if I click on No??) and just gets in the way of the whole reading experience, when you just want to focus on what the documentation is trying to tell you.  All in all: horrible.

**Comment by dend** [comment]
Fixed with f38eaa3fb447990da9ca0b8406bb4c6c30215a2a.
