### ISSUE TITLE
Add licensing information

### ISSUE THREAD

**Issue by ReedCopsey** [Microsoft/visualfsharpdocs#5]
There is currently no licensing information attached to any of these docs.  It'd be nice to know whether they'd be reusable by other projects, and if so, under what license.

**Comment by NumberByColors** [comment]
Looking into it...

**Comment by ReedCopsey** [comment]
@NumberByColors Having a license file at the root level would be standard - headers would be nice, but even if they're left out, at least there would be a reference document there.

**Comment by dend** [comment]
+1 to what @ReedCopsey mentioned.

I will script the license as headers and will include it both at a root level and inside .MD files.

**Comment by dend** [comment]
License is now included in the repo.

**Comment by dend** [comment]
Added the code license as well in the repo.
