### ISSUE TITLE
Exceptions tag is not supported!!!!The result sequence.

### ISSUE THREAD

**Issue by KevinRansom** [Microsoft/visualfsharpdocs#81]
This page has the text:
exceptions tag is not supported!!!!The result sequence.

https://msdn.microsoft.com/visualfsharpdocs/conceptual/seq.map%5b%27t%2c%27u%5d-function-%5bfsharp%5d

**Comment by ReedCopsey** [comment]
There are actually a lot of these.  Also, code tags not supported.  Trying to clean them up as I go through the "bad translation" stuff from the XML doc comments as part of #61 .

**Comment by dend** [comment]
@KevinRansom @ReedCopsey Yup. Looking at some of those now.

**Comment by dend** [comment]
@KevinRansom @ReedCopsey identified a way to fix those. Working on it. Current batch in #140.

**Comment by dend** [comment]
This should be covered by #163 to fix all exception errors.

Once the PR is merged, I will close this.

**Comment by dend** [comment]
PR has been merged.
