### ISSUE TITLE
Plane text is formatted as code snippet

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharpdocs#96]
https://msdn.microsoft.com/visualfsharpdocs/conceptual/match-expressions-%5bfsharp%5d

![image](https://cloud.githubusercontent.com/assets/873919/15566924/2e3dea9a-232c-11e6-8793-466b0fea92e0.png)

and here https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/units-of-measure-[fsharp]

![image](https://cloud.githubusercontent.com/assets/873919/15567011/a1b1430a-232c-11e6-9a0d-0d700502b53f.png)

**Comment by dend** [comment]
@ReedCopsey fixed that. Thanks both once again!
