### ISSUE TITLE
Broken link in "Lazy Computations"

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharpdocs#98]
https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/lazy-computations-[fsharp]

at the end

![image](https://cloud.githubusercontent.com/assets/873919/15567064/e11abb84-232c-11e6-9ce0-678a65329dec.png)

**Comment by dend** [comment]
Looks like @ReedCopsey fixed that with his PR. Thank you both!
