### ISSUE TITLE
Massive wrong indentation in snippets, plane text is formatted as code

### ISSUE THREAD

**Issue by vasily-kirichenko** [Microsoft/visualfsharpdocs#99]
https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/let-bindings-[fsharp]

![image](https://cloud.githubusercontent.com/assets/873919/15567128/3bd32192-232d-11e6-8e35-dc593ac748b9.png)

**Comment by vasily-kirichenko** [comment]
Also in "Code formatting guidelines" https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/code-formatting-guidelines-[fsharp]

![image](https://cloud.githubusercontent.com/assets/873919/15567764/d8d3c778-2330-11e6-8932-9a9dfbbaa633.png)

**Comment by dend** [comment]
Fixed in #128
